### ISSUE TITLE
Generic List other than List<Object> does not properly serialized

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast-csharp-client#100]
writing from c#

 ```
var map1 = client.GetMap<string, List<int>>("listTest");
map1.Set("vikTest", new List<int> {1, 2});
```

can’t read it from java

`Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type -110. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.`

but it should use `type -26` which is List

**Comment by cangencer** [comment]
If you use `-26` for both `List<int>` and List<object>` then in C# you would be putting a `List<int>` to a map, but getting a `List<object>` back when you query it.

So this code would throw casting exception:

```
map1.Set("vikTest", new List<int> {1, 2});
List<int> value = map1.Get("vikTest");
```
