### ISSUE TITLE
Error while compiling the Hazelcast.Test project 

### ISSUE THREAD

**Issue by Vishwanathbk1** [hazelcast/hazelcast-csharp-client#109]
Hello,

I am trying to create hazelcast dot net client.
While compiling the test project I am getting the below error:

Error	13	Friend access was granted to 'Hazelcast.Test, PublicKey=00240000048000009400000006020000002400005253413100040000010001004d81045a994968ac643918d7bbce405b2473471d8de6aed6bbffc0fe1874bfcabf3c0b437c6c5293a589bdcbe884c6d86934069b35deaf5ab2e770cbff41a20dd4014bb53e481c30bd3ead29437b02dec5916a717a4a2b4fd353e81238b89ae09e5ba0ab615c5fef7937aabab4e240c3dffe2b948047769eeb07f674589d0bb3', but the output assembly is named 'Hazelcast.Test, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null'. Try adding a reference to 'Hazelcast.Test, PublicKey=00240000048000009400000006020000002400005253413100040000010001004d81045a994968ac643918d7bbce405b2473471d8de6aed6bbffc0fe1874bfcabf3c0b437c6c5293a589bdcbe884c6d86934069b35deaf5ab2e770cbff41a20dd4014bb53e481c30bd3ead29437b02dec5916a717a4a2b4fd353e81238b89ae09e5ba0ab615c5fef7937aabab4e240c3dffe2b948047769eeb07f674589d0bb3' or changing the output assembly name to match.	d:Hazelcast.Net\bin\Debug\Hazelcast.Net.dll	Hazelcast.Test

Also, I want to connect to the Hazelcast cache server, which password protected. Please let me know how to do this.

Thanks.

**Comment by asimarslan** [comment]
In order to build hazelcast .net client one should setup the Strong name generation. See the main readme on this repo.
