### ISSUE TITLE
Decrement Pending packets for events also

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-csharp-client#14]
An issue found in java client.
https://github.com/hazelcast/hazelcast/pull/6608
Needs to be checked if same issue is here.

**Comment by cangencer** [comment]
This should not effect the new client as it does not use packet counting for keeping track of pending messages.

**Comment by sancar** [comment]
For your information , this is applicable to new client on java side. I made the fixes for new client also hazelcast/hazelcast#6608.
