### ISSUE TITLE
Listening to Map Entries with Predicates with hazelcast.map.entry.filtering.natural.event.types enabled does not work

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#145]
I try to use [map listener with predicates](http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/Map/Listening_to_Map_entries_with_Predicates.html) like on docs.

I am using .net 3.9 client and I configured my Java (also Hazelcast 3.9) code. But my listeners doesn't fire. 
`            myTestMap.AddEntryListener(new EntryAdapter<string,MyTestMap> {
                Added = e => ValidateData(e)  },new SqlPredicate("Status=2"),true);`

> When old value does not match predicate, new value matches predicate 

writes on document. But any event fire include with have no predicate.

**Comment by iozcelik** [comment]
I update version 3.9.1 and try to use `EntryAddedListener`. I update code;

```
MyTestMap.AddEntryListener(new TestListener(),new SqlPredicate("Status=2"),true);
public class TestListener: EntryAddedListener<string,MyTestMap> {
    public void EntryAdded(EntryEvent<string,MyTestMap> @event) {
         ValidateData(@event);
    }
}
```
This time, I get:

> Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).

**Comment by iozcelik** [comment]
Ok, I found the problem and try to fix it.

`ClientMapProxy.AddEntryListener(MapListener listener,.....`
methods has recursive call so, I get previous exception.

I remove recursive calls and put the code (previous listener code) and it's seem working without predicate. But when using predicate, still is not working.

**Comment by asimarslan** [comment]
We need to validate `hazelcast.map.entry.filtering.natural.event.types` works or not. I'll write unit tests for it.

**Comment by asimarslan** [comment]
We fixed the listener registration making recursive call in v3.9.2. 

This issue only represent the natural filtering of events configured on server side with `hazelcast.map.entry.filtering.natural.event.types = true` behaviour on .net client side.

See [Hazelcast ref manual](http://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#listening-to-map-entries-with-predicates) for the expected behaviour.

**Comment by emreyigit** [comment]
Predicates deprecated.
