### ISSUE TITLE
MapListener fired about 30 seconds later

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#146]
I used to map listener in my project. Previous version of Hazelcast fired immediatly but 3.9.1 version fired listener about 30 seconds later. My code still same? What's change? Could I miss something?

**Comment by asimarslan** [comment]
Can you provide a sample code that repoduces the case.

**Comment by iozcelik** [comment]
My Listener Code;

```
var myMap= hzInstance.GetMap("myMap");

myMap.AddEntryListener(new EntryAdapter<string,MyEntity> { Updated = e => { 
      EntityUpdated(e); 
}, },new SqlPredicate("status=1"),true);
```

It is fired, no problem in there but it takes about 30 seconds, even sometimes 1 minute.

**Comment by stalek71** [comment]
@iozcelik ,
could you tell me how did you measure that time?
Is it the case you constructed the client instance, added the listener 
and then you sent some value to the map?
After the sending a value to the map you were waiting for the activation of EntityUpdated() method, right? The time you measured started at client construction time and ended at method activation, right?

**Comment by stalek71** [comment]
It's related to old client version but the way you measured it can help me to verify what was your case...

**Comment by emreyigit** [comment]
Closed due to expiration and architectural changes between 3.x and 4.x
