### ISSUE TITLE
Heartbeat requests suddenly stopping to cluster members

### ISSUE THREAD

**Issue by rvenancio** [hazelcast/hazelcast-csharp-client#153]
The C# client (version 3.9.1) is connecting successfully to server nodes (also 3.9.1). After that, It starts sending heartbeat requests to the server nodes, but in about 2minutes it suddenly stops as we can see in the following logs.

> 2018-02-08 17:42:35.6516 |Debug ||||Sending heartbeat to Connection[0][IMember [10.131.22.75]:5712 -> 10.2.22.9:49375];
> 2018-02-08 17:42:35.6516 |Debug ||||Sending heartbeat to Connection[2][IMember [10.131.22.15]:5712 -> 10.2.22.9:49377];
> 2018-02-08 17:42:35.6516 |Debug ||||Sending heartbeat to Connection[4][IMember [10.2.22.43]:5712 -> 10.2.22.9:49379];
> 2018-02-08 17:42:35.8232 |Debug ||||Updating partition list.;
> 2018-02-08 17:42:35.8232 |Debug ||||Partition list updated;
> 
> 
>
> 2018-02-08 17:47:37.3372 |Warn ||||Got exception in connection Connection[0][IMember [10.131.22.75]:5712 -> 10.2.22.9:49375]:; Error message: Target[Address[10.
> 131.22.75]:5712] disconnected, Socket was closed.;  Hazelcast.Client.Spi.TargetDisconnectedException: Target[Address[10.131.22.75]:5712] disconnected, Socket wa
> s closed.
> 2018-02-08 17:47:37.3528 |Debug ||||Destroying connection Connection[0][IMember [10.131.22.75]:5712 -> 10.2.22.9:49375] due to Target[Address[10.131.22.75]:5712
> ] disconnected, Socket was closed.;

After 5minutes, the server nodes kick the client due to inactivity.

Anyone is also facing this issue?

**Comment by simpleusr** [comment]
Hi @rvenancio ,

It seems that we are facing the same or a similar issue? 

https://github.com/hazelcast/hazelcast-csharp-client/issues/170

Did you find a solution?

Regards

**Comment by asimarslan** [comment]
Duplicate issue. Closing this one and followup with #170
