### ISSUE TITLE
NuGet Version 3.9.2 has issue [Strong name signature could not be verified]

### ISSUE THREAD

**Issue by wangsu** [hazelcast/hazelcast-csharp-client#158]
Reverted to Version 3.9.1 and this issue gone. 

Must be something wrong on NuGet dll.

Error Message:
Could not load file or assembly 'Hazelcast.Net' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

![screenshot-1](https://user-images.githubusercontent.com/2042168/36602168-55b1e6da-1885-11e8-86b8-7f53ae1bf330.png)

**Comment by rvenancio** [comment]
I am facing this problem too.

**Comment by JMonono** [comment]
Just to confirm I am experiencing the same issue when attempting to reference the 3.9.2 NuGet package in a (WCF) Web Application. I tried to skip verification for the assembly by using the Strong Name tool (sn.exe) and by adding several entries to the registry, and still experience the same issue.

Happy to provide more details if it helps.

**Comment by ercanacar** [comment]
anybody on there ?

**Comment by ercanacar** [comment]
same building error.

**Comment by iozcelik** [comment]
Same here, I use Hazelcast 3.9.3

**Comment by asimarslan** [comment]
Fixed in 3.9.4 release.
