### ISSUE TITLE
C# client FlakeIdGenerator missing

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#164]
I use hazelcast c# client 3.9.3 and I dont find flakeIdGenerator. Is it working only with java?

**Comment by burakcelebi** [comment]
Thanks, @iozcelik. This is on our .NET client roadmap. I personally expect this can be shipped in 2019. 

Currently, you can use FlakeIdGenerators via Java, C++, Node.js, and Go clients. Please see the feature comparison table for clients: https://hazelcast.org/clients-languages

**Comment by iozcelik** [comment]
Currently we use only .net client. And a simple java server code. Probably, I will wait. Currently some features including flakeIdGenerator are missing at .net client.

**Comment by dbrimley** [comment]
I'm going to close this issue as it is on our road-map for 2019.

**Comment by burakcelebi** [comment]
Duplicate of https://github.com/hazelcast/hazelcast-csharp-client/issues/292
