### ISSUE TITLE
Hang/deadlock on map put/set

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-csharp-client#171]
On large-scale runs on a 12-node cluster, a user finds small numbers of instances of a C# client API call not returning from a put or set to a map: a hang or deadlock, or perhaps a stale client connection. 

They face this issue infrequently, 5-10 occurrences in a batch run of 500 jobs say, each of which would be making map set calls on average, for instance, 500 times. Bit of a rough-and-ready calculation, but it would be one call per many thousand. 

One symptom would be from this code: 

```
Log.InfoFormat("First log line"); 
Cache.Insert(...); 
Log.InfoFormat("Second log line");
```

The second log line is not executed (and nor is any subsequent code), and the process never terminates.

The `Cache.Insert` call resolves to this (where `CacheKey` is an `IPortable` containing two string properties, and `GetCache` returns the IMap instance for the named cache form a dictionary):

```
public void Insert(string cacheName, CacheKey cacheKey, ICacheable value) 
{ 
      IMap<CacheKey, ICacheable> cache = GetCache(cacheName); 
      if (cache != null) 
      { 
             cache.Set(cacheKey, value); 
      } 
} 
```

The following properties are used as default:

```
hazelcast.client.invocation.timeout.seconds: 120s 
hazelcast.client.heartbeat.timeout 300000ms 
hazelcast.operation.call.timeout.millis 60000ms 
hazelcast.socket.connect.timeout.seconds 0ms
```

**Comment by sertugkaya** [comment]
related ZD tickets 4032 and 6122

**Comment by zpqrtbnk** [comment]
Moving from milestone 4.0 to Support - this was a 3.x issue that cannot be reproduced on 4.0 at the moment.

**Comment by zpqrtbnk** [comment]
Closing.
