### ISSUE TITLE
No way to get IHazelcastClient Status ?

### ISSUE THREAD

**Issue by tebeco** [hazelcast/hazelcast-csharp-client#172]
In order to get a healthchack on the `HazelcastClient` i'm trying to monitor the connection to the cluster.
The only way i found is :

```
            _hazelcastInstance =HazelcastClient.NewHazelcastClient(clientConfig);
            _hazelcastInstance.GetLifecycleService().AddLifecycleListener(new LifecycleListener((e) =>
            {
                hzHealthCheck.IsClientConnected = (e.GetState() == LifecycleEvent.LifecycleState.ClientConnected);
            }));
```
This looks fine but it is kinda stupid since the client attempt to connect on this line :

```
            _hazelcastInstance =HazelcastClient.NewHazelcastClient(clientConfig);
```
And the cluster could be up or down it will never raise the event ... so until a real event happens the healthcheck would be useless right ?

@asimarslan @cangencer not sure if there are better place to look for that info elsewhere

**Comment by asimarslan** [comment]
Hi @tebeco ,

You need to configure your lifecycle listener in the config such as :
```
            clientConfig.AddListenerConfig(new ListenerConfig(new LifecycleListener(e =>
            {
                hzHealthCheck.IsClientConnected = (e.GetState() == LifecycleEvent.LifecycleState.ClientConnected);
            })));
            var client = HazelcastClient.NewHazelcastClient(clientConfig);

```

so that when the client start the lifecycle listener would be already configured and won't miss an event.

**Comment by tebeco** [comment]
yeah this is what i ended up doing
i still wonder why not raisin the event ?
also why using a static factory instead of a constructor
for unit test this is hell on earth because of that
since trying to create mock over ` public static Stuff X()` is kinda hard
kinda funny to see that under the hood it’s just a `ProxyHazelcastClient`
that tries to map call to the “real” client
“tries” because there’s hidden `throw new NotSupportedException`

it’s kinda hard to understand how the code is designed

**Comment by sancar** [comment]
> i still wonder why not raisin the event ?

It should raise the event. Are you asking why it did not raise the event before when you add the listener after instance crated ?

> also why using a static factory instead of a constructor

This way all API entry points are gathered in single point. When you say "HazelcastClient." , your ide shows all the things that you can do. Creating a map from hazelcast is also same. We could have done
`new IMap(hazelcastClient, mapName)`
But  we choose to do
`hazelcastClient.getMap("mapNaoe")`

Also with static context, we can keep track of all the clients started and give API like `shutdownAll` 

In the end, it is a matter of taste. We could have choose the other way around. 

> since trying to create mock over public static Stuff X() is kinda hard

I did not get why it cause you trouble though. Which class are you trying to mock ?

**Comment by tebeco** [comment]
> It should raise the event. Are you asking why it did not raise the event before when you add the listener after instance crated ?
My point is that if the `ClientLifecycleListenner` does not receive the event `connected` may be when any `ClientLifecycleListenner` is added it would be a good idea that the SDK push an event with the current state

The best idea is that you really should exposed the `State` on the `HazelcastInstance` returned by the `CreateClient`

My point over all the `static` stuff is that ... in short ... this is a really bad design and it is ugly ;)
on top of it, the `CreateClient` is a blocking call and it is a lie :
* It creates a client
* It connect the client
* It could block the code execution (or the attempt the kill the process in some scenario when there is no cluster)
* we should be able to

```
IHazelcastClient client = new HzClient(clientConfig) //<== NO CONNECTION and return an interface
await client.ConnectAsync(cts) // <== Handle Cancellation token so that i could kill it when i want
```

that way any Substitute / Moq framework would be able to properly create mock
Again "Depend on Abstraction, not on implementation"
This would also allow API Consumer to extends the client :
* I cannot add telemetry over the `HazelcastClient` since i have to pass the `sealed` implementation
* I cannot simulate exception in my `UnitTest` like if `GetMap()` throw (no cluster, no map but clustter, wrong serializer, wrong tpye, corrupted data ....)
* I have to run Hazelcast for unit test ? so all unitest are now integration test when a simple interface would have sloved it all
