### ISSUE TITLE
Add custom Hazelcast client instance name from ClientConfig

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-csharp-client#175]
The users want to set custom client instance name in order to track them on Management Center. This feature already exists on Java clients (https://github.com/hazelcast/hazelcast/pull/5605).

**Comment by zpqrtbnk** [comment]
This is implemented in the upcoming version 4.0 of the client. I believe this issue can be closed, but feel free to open a new issue if you think otherwise.
