### ISSUE TITLE
Best practice to serialization nullable values

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#196]
Most of classes use nullable types. Which serialization method is better do it?  How we keep nullable values at Map?
```
class TestClass {
     public int NonNullableInt { get; set; }
     public int? NullableInt { get; set; }
     public string MyText { get; set; }
     public decimal? NullableDecimal { get; set; }
}
```

**Comment by asimarslan** [comment]
Hi @iozcelik,

Hazelcast .Net Client support these builtin primitive types:
```
bool
byte
char 
short 
int 
long
float 
double
```
You can use nullable counterparts of the above types whereever you need. Internal representations are identical. Only null values are handled differently and non-null values would be same as non-nullable types due to c# feature.

For example, if you type check `int`  with `typeof(int)` and `typeof(int?)`, both would give `Sytem.Int32`.

Please note that there is no builtin support for `decimal` or `decimal?` type. 

I'll add a null related subsection to [documentation](https://github.com/hazelcast/hazelcast-csharp-client#4-serialization)

**Comment by iozcelik** [comment]
> Only null values are handled differently
Ok, my point is that. How can I write and read portable null values to Hazelcast?

**Comment by asimarslan** [comment]
Hazelcast IMap does not support null values. You need to wrap it with a non null class. If you are asking the null portable values within portables then there is an [API](https://docs.hazelcast.org/docs/clients/net/3.10.0/html/M_Hazelcast_IO_Serialization_IPortableWriter_WriteNullPortable.htm) for it.

**Comment by iozcelik** [comment]
I think wrapping is not best solution because that entities will be mapping to others. So hazelcast need to handle it own side with a flag.
For example;
writer.WriteLong("size", 10000);
method will be change below like:
writer.WriteNullableLong("size", null,true); //the last paramater is check that is null. I could check to my property is null.
writer.WriteNullableLong("size", 10000,false);

Hazelcast could not write null, it could write long.MinValue or 0 for null. That's not important if a bool parameter add for null check.

And read like:
var value = reader.ReadNullableLong("size",out bool isNull);
if(isNull){
           size=null;
}else{
         size=value;
}

**Comment by asimarslan** [comment]
Hi @iozcelik,

I'll rephrase my previous statement as I think there is a misunderstanding.

Hazelcast does not support null values for Hazelcast map.
example:
```
map.Put("key", null); //will receive null pointer exception
```

For IdentifiedDataserializable types, nullable types on the fields can be used in two ways:

The first method; treat them as object types

```
public class Sample1 : IIdentifiedDataSerializable
{
        private int? _nullableInt;
        
        public void ReadData(IObjectDataInput input)
        {
            _nullableInt = input.ReadObject<int?>();
        }

        public void WriteData(IObjectDataOutput output)
        {
            output.WriteObject(_nullableInt);
        }

...
```

Second method; using two fields where first is a boolean that represents the null case:
```
    public class Sample2 : IIdentifiedDataSerializable
    {
        private int? _nullableInt;
        public void ReadData(IObjectDataInput input)
        {
            var isNull = input.ReadBoolean();
            _nullableInt = isNull ? (int?) null : input.ReadInt();
        }

        public void WriteData(IObjectDataOutput output)
        {
            if (_nullableInt == null)
            {
              output.WriteBoolean(true);  
            }
            else
            {
              output.WriteBoolean(false);
              output.WriteInt(_nullableInt.Value);
            }
        }
  ...

```
