### ISSUE TITLE
Feature Request: Extensions Packages for ASP.NET Core

### ISSUE THREAD

**Issue by ryanelian** [hazelcast/hazelcast-csharp-client#198]
My company is exploring Hazelcast for deploying a distributed in-memory cache for Windows-only-no-Docker customers. (Since native Redis requires Linux...)

The official Microsoft package supports implementation of `IDistributableCache` to Redis:

https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1

https://github.com/aspnet/Caching/tree/b7cda012bca34704e5a835ace53a0f879b5f2a2d/src/Microsoft.Extensions.Caching.StackExchangeRedis

And Data Protection key storage provider to Redis:

https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.StackExchangeRedis

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1

https://codeopinion.com/asp-net-core-data-protection/

https://github.com/aspnet/AspNetCore/tree/master/src/DataProtection/src/Microsoft.AspNetCore.DataProtection.StackExchangeRedis

And scaling out SignalR using Redis store:

https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.StackExchangeRedis

https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis

https://github.com/aspnet/SignalR/tree/b5543a4d79d813c33d5cd6cdff3a2605aafde432/src/Microsoft.AspNetCore.SignalR.StackExchangeRedis

It would be amazing if Hazelcast C# client also provides the official implementations for above features for ASP.NET Core. 😃

**Comment by dbrimley** [comment]
Hi @ryanelian,

So I can clarify the features you are asking for....

(1) A Hazelcast provider for `IDistributableCache`.  From what I can see this looks like a Microsoft library/interface that is distributed by default in ASP.NET?

(2) A Hazelcast implementation of the Data Protection Key Storage Provider

(3) A SignalR implementation that uses Hazelcast as the messaging infrastructure.  I'm assuming SignalR has interfaces that plug-in Hazelcast .Net Clients?

It looks like all of these need a Hazelcast .Net Client embedded with a proxy for the interfaces onto the cluster.

Is this something you would like to contribute to the codebase?  I'm sure we could help you get started on this in collaboration with one of our engineers to guide you?  That is if your company are willing to allow some time to do this with us?

**Comment by dbrimley** [comment]
Hi @ryanelian, you closed this issue?  Is it no longer required?

**Comment by ryanelian** [comment]
Hi,

Yes I did close the issue.

I am simply no longer interested in Hazelcast.

**Comment by sunsided** [comment]
I, on the other hand, am very much interested in this one. :slightly_smiling_face: While working on this myself I stumbled upon the problem that the `IDistributedCache` interface understands the notion of sliding expiration, where accessing an item would extend the TTL for it. I haven't found a good way to do this, so far; my use case is to cache files within Hazelcast.
