### ISSUE TITLE
GlobalSerializer Sample - not actually doign anything ?

### ISSUE THREAD

**Issue by tebeco** [hazelcast/hazelcast-csharp-client#202]
Hello,

We are trying to use the `GlobalSerializer` feature but after reading the sample :
https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Examples/Org.Website.Samples/GlobalSerializerSample.cs#L33-L43

It seems that even your code does not provide working sample ;)

We have tried multiple attempts to make it work with a simple `Newtonsoft.Json` to serialize / deserialize any kind of `<T>` to json stringified but the API from this lib is a totally mistery
We hit lots of
* `OutOfMemoryException` (your lib tried to allocation `byte[maxInt]`)
* we could not access the data length
* We had exception saying `you reach the end of the stream allready`

etc ...

can you provide an actual running sample for `GlobalSerializer` ?
The idea is simple, take ANY kind of type, and use `Newtonsoft.Json` to convert it to json string and back to object when attempting to read it back

**Comment by asimarslan** [comment]
Hi @tebeco,

Thanks for the request. This sample is created for website display purpose and kind of generic.
I added another sample for your case.

Please see: #207

**Comment by tebeco** [comment]
thx you very much for your time and the sample
will read that carefully

closing this issue ;)
