### ISSUE TITLE
.net MapStore implementation

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#208]
Has any plan to implement MapStore to .net client?

**Comment by dbrimley** [comment]
Hi

`MapStore` does not run on any clients. `MapStore` runs on the hazelcast member(s) within the cluster, all cluster members run Java.

Regards
David

**Comment by iozcelik** [comment]
Why not MapStore working on clients?

**Comment by dbrimley** [comment]
MapStore is a cluster side interface that works directly with cluster members.

**Comment by iozcelik** [comment]
I got it. However, Hazelcast need to a client side replication of MapStore.

In my case my hazelcast member cannot access the database server. But I have a Hazelcast client on that server. So, if hazelcast has a MapStore for clients, I do not need to write my custom. But now I handle it. 

If Hazelcast want to improve ownself, I think that request will be in backlog.

**Comment by dbrimley** [comment]
I think what you're looking for is something like the [cache aside pattern](https://blog.cdemi.io/design-patterns-cache-aside-pattern/), where you update entries in the cache and the client is responsible also for getting and putting to the database.

**Comment by iozcelik** [comment]
In current state, I use it but I prefer Hazelcast has native support  like other inmemory solutions.

**Comment by dbrimley** [comment]
Could you direct me to the reference manual of MongoDB where this is described?

**Comment by iozcelik** [comment]
Actually, I use ignite and I think they explain [here](https://apacheignite.readme.io/docs/distributed-persistent-store)

**Comment by dbrimley** [comment]
That's binary disk persistence not a map store.  A map store enables you to connect a cluster member up to some other kind of underlying store like a NoSQL database.

**Comment by iozcelik** [comment]
Ok right but MapStore or binary map persistence, either one still solve my problem. Of course MapStore doesnt solve all problems but I think I could use it. 

As I remember, Hazelcast does not persist. So I open this issue as MapStore.
