### ISSUE TITLE
MultiAttributeProjection implementation

### ISSUE THREAD

**Issue by iozcelik** [hazelcast/hazelcast-csharp-client#214]
Is there a plan for built-in MultiAttributeProjection implementation? Or, how I could use Class Projection<I,O> with transform method to implement my own.

**Comment by burakcelebi** [comment]
Hi @iozcelik, thanks for your request! I'm now monitoring this type of requests closely. Sorry for our late response.

We believe it was not implemented due to a technical limitation. @stalek71 will clarify it, and update you accordingly. Based on his research, we can add this to our backlog.

Cheers.

**Comment by stalek71** [comment]
Hi @iozcelik ,
there is no plan to provide built-in MultiAttributeProjection at the moment (but it varies). 
Please check the implementation of `SingleAttributeProjection` on our [git repo](https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Net/Hazelcast.Core/Projection.cs)
In short on the client side you have to serialize params for a transformation you run on the server/cluster side. How it's implemented on server side(sample implementations) you can check [here](https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast/projection/impl).   
Please just check how `SingleAttributeProjection` client side interacts with server side and based on this create your own transformations/projections.  
For generic questions about the client lib usage please use [StackOverflow](https://stackoverflow.com/questions/tagged/hazelcast) or our [google group](https://groups.google.com/forum/#!forum/hazelcast)

**Comment by iozcelik** [comment]
I think this issue will open again. Because still there is no solution.

**Comment by zpqrtbnk** [comment]
The multi-attribute projection will be available in the upcoming 4.0 client.
