### ISSUE TITLE
Add parametrized Lock() and Unlock() operations

### ISSUE THREAD

**Issue by stalek71** [hazelcast/hazelcast-csharp-client#222]
Some programming languages (like C# for instance) support execution of a processing flow on many threads. Typical case is usage of async/await keywords where the code part before an await keyword is executed by one thread and the part after await keyword is executed by other/second thread. 
In case we stick to thread id during locking only we loose ability to continue processing on many thread as a continuous flow. 

The option could be to add api like Lock(int) or Lock(string) so in single method with a flow divided between many consecutive threads we still know id of a lock owner and can use it from any "continuation" thread.

**Comment by zpqrtbnk** [comment]
Version 4 of the .NET client (currently in BETA) is fully asynchronous and fully relies on async/await calls. The lock ownership strategy used in version 3 (thread identifier) becomes therefore totally irrelevant, as you have discovered. Version 4 of the .NET client introduces a new, context-based, lock ownership strategy which works with async/await.

I'll point you to the relevant documentation as soon as it is online.

**Comment by emreyigit** [comment]
The documentation can be found here http://hazelcast.github.io/hazelcast-csharp-client/latest/doc/locking.html
