### ISSUE TITLE
Convert IDS#getId to getClassId

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-csharp-client#239]
IdentifiedDataSerializable's getId is renamed to getClassId on 4.0. Csharp should follow the same approach when 4.0 is released.
https://github.com/hazelcast/hazelcast/pull/15127

**Comment by zpqrtbnk** [comment]
We are about to release version 4.0 of the Hazelcast.Net client, and the code has been vastly refactored, rendering this issue... unfortunately irrelevant. In fact, `IIdentifiedDataSerializable` now defines a `int ClassId { get; }` property.

This issue can be closed.
