### ISSUE TITLE
Missing "LOADED" event

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-csharp-client#243]
See https://github.com/hazelcast/hazelcast-go-client/issues/464

IMDG 3.11 added LOADED event - https://docs.hazelcast.org/docs/3.12.1/javadoc/com/hazelcast/core/EntryEventType.html#LOADED

This is not handled by this client

**Comment by zpqrtbnk** [comment]
This is a 3.x issue, and 3.x is now in maintenance mode, as we work on the upcoming 4.x version. In 4.x, the *Loaded* event is supported (see [HDictionaryEventTypes](https://github.com/hazelcast/hazelcast-csharp-client/blob/master/src/Hazelcast.Net/Data/HDictionaryEventTypes.cs)) so I am going to close this issue. Please raise a new issue in case of concerns.
