### ISSUE TITLE
Clear map without type?

### ISSUE THREAD

**Issue by Menighin** [hazelcast/hazelcast-csharp-client#265]
I'm creating several maps to cache some info for my application.
When some events are triggered I want to clear those caches.
I have a list of all maps names I should clear but I couldn't find a way to dynamically get those maps without the types to clear them.

In the README.md we have some examples like:

```
var client = HazelcastClient.NewHazelcastClient();

var personnelMap = client.GetMap("personnelMap");
personnelMap.Put("Alice", "IT");
personnelMap.Put("Bob", "IT");
personnelMap.Put("Clark", "IT");
Console.WriteLine("Added IT personnel. Logging all known personnel");
foreach(var entry in personnelMap.entrySet())
{
    Console.WriteLine("{0} is in {1} department", entry.Key, entry.Value );
}
client.Shutdown();
```

That indicates we should have a method `GetMap` that is non-generic but I couldn't find it. The only one avaiable is `GetMap<TKey, TValue>`. Are the docs wrong? Is there a way to get a `Map` by its name without using some ugly reflection?

Thx

**Comment by Scooletz** [comment]
Currently, I see no way of doing it. We could add an intermediate non-generic `IMap` interface and move all the non-generic method in there, but currently it's not supported.

**Comment by zpqrtbnk** [comment]
If I understand correctly, what you want is to fully clear the map, right?

Nothing prevents you from getting the map as `client.GetMap<object, object>("map")` - and then `map.Clear()` - as long as you don't read/write the map, that should be safe.

Would this help? Is this issue still relevant?

**Comment by Menighin** [comment]
Hi @zpqrtbnk,
The issue is no longer relevant... I no longer work on that project, but that seems like it would work...
Thanks!
