### ISSUE TITLE
Application throw when attemting gracefull shutdown if client never connected [API-2054]

### ISSUE THREAD

**Issue by tebeco** [hazelcast/hazelcast-csharp-client#285]
Hello,

As of today there's no way to pass a `CancellationToken` when calling 
`var client = HazelcastClient.NewHazelcastClient(config);`
Could you add it to the Api when creating an `HazelcastClient` ?
`var client = HazelcastClient.NewHazelcastClient(config, myOwnCancellationToken);`
That way i could properly pass on the existing `StoppingToken` from AspNetCore, or my own if i have to decide of the lifetime
the big issue here is that Hazelcast is mainly `Blocking/Sync` Api without proper counter measure for the consumer on edge case

# Repro
if you create an aspnetcore app :
`dotnet new webapi`

(pseudo code)
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHostedService<HzClientService>();
    }
}

/////
public class HzClientService : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await Task.Yield();

            var clientConfiguration = new ClientConfig();
            clientConfiguration.GetNetworkConfig().AddAddress(new [] { "localhost:5701", "localhost:5702"});

            clientConfiguration.GetNetworkConfig().SetRedoOperation(true);
            clientConfiguration.GetNetworkConfig().SetConnectionAttemptLimit(50);

        var client = HazelcastClient.NewHazelcastClient(clientConfiguration);
    }
}
```

* DO NOT START THE CLUSTER, 
* Configure the IDE to run in the `Console` and not IIS Express and press F5
* Wait for the console to show, and wait like 5 sec (so that it should to few retry
* Press `Ctrl+C` in the console to trigger a Gracefull shutdown

It will not be gracefull one and will throw :(
![image](https://user-images.githubusercontent.com/2266487/78196249-154a9000-7482-11ea-97cd-ea4015d05685.png)

![image](https://user-images.githubusercontent.com/2266487/78196136-ba189d80-7481-11ea-91ae-6cd6a85ee53e.png)

**Comment by tebeco** [comment]
hello @burakcelebi 
out of curiosity, can you tell me if there is another label that `Type: Enhancement` ? i wonder what means `Defect` to you

As it will be something new, it would somehow be an enhancement, but as of today the call is blocking and litarelly never returns until it does connect.
Also in such scenario,
* it will NEVER connect
* Consumer cannot stop the app
* The Lib (a third part) throw an exception when you try to do a graceful shutdown
* Deployment are affected since a Throw + exit code not being 0 are very very bad
* Consumer cannot / must not handle that exception to attempt to understand if this is very very specific scenario or soething that, so there's no clean way to silent this exception because we did ask for a GRAEFULL shutdown, and there's no way to inform `Hazelcast.Create(...)` about that GRACEFULL 
* The library is probably doing Async Over Sync which is ultimately yet another problem in `dotnet`

As of today it's really look like `Type: Critical` (again no idea if it could be `Defect` or not)

**Comment by burakcelebi** [comment]
Hi @tebeco, I'm sorry about this and I understand you. I'll remove the label and escalate it to our lead developer, Stephan (@zpqrtbnk).

**Comment by zpqrtbnk** [comment]
Hey. Stephan here, lead dev for the client.

I understand what you mean. First, as a general observation, none of the API is async-friendly. Second, in this precise case, there is no way to kill the client properly if it cannot connect.

The key issue is the first one. If you look at the code you'll see that the library indeed "*probably doing Async Over Sync*" and vice-versa, making it hard to just fix the precise client issue.

Refactoring the library to be generally async-friendly is currently in progress (too soon for an ETA) and I'll keep this issue open to make sure it is addressed.

**Comment by tebeco** [comment]
hello @zpqrtbnk 
Thx for the quick answer here.

It's fine if it's not Async yet, the thing is that there's already a `CancellationToken/Source` manually created inside `Hazelcast.Net` in fact, but it's just a `var cts = new CancellationTokenSource()` and it seems to be used internally for cancellation

I think it might actually be possible to exposed an overload accepting a `CancellationToken/Source` and Merge these 2 together so that we would be able to trigger a Cancellation request.

That would fix the issue fast, while your team works on the async refactoring on the next version (that would also be possible to land that fix for customer still using v3.x while i guess the refactoring will land on v4.x)

**Comment by tebeco** [comment]
What do you think ?

Also, will 4.x Client library designed to be compliant with 3.x (~latest) cluster ?

**Comment by tebeco** [comment]
also not sure, as the `Enhancement` was removed, I think it need to be flagged with `Defect` right ?
The end result today is that:
* Exit code it definitly not `0`
* Customer can do a `Try/catch` on `Main()` because one of their third-part implosed on Gracefull shutdown
* Monitoring tool goes red and could try to rollback deployement, when this issue was for example a typo in the `nodes address` (not able to connect)

What I mean is that the real source, is customer but the "shown behavior" by the `Hazelcast Client` is definitly not the one anybody could expect, this is why this would be a `Defect` ==> crash on shutdown is definitely not wanted by anyone

![image](https://user-images.githubusercontent.com/2266487/80345151-fc5ab200-8868-11ea-932b-013cc62cfd8c.png)

**Comment by zpqrtbnk** [comment]
I think we can reasonably consider this a defect. While it will be fixed in the long run with v4, we could investigate whether there is indeed a "quick fix" for it in the v3 branch. @burakcelebi ?

**Comment by tebeco** [comment]
based on the discussion here #288 
There's chances it could/will take time for people to migrate (maybe even more for open source as they would need either a totally synchronization, or a "manual solution")
So the potential issue could lives on years sadly.

I'm not even sure we'll be allowed to update to `v4` for example

**Comment by tebeco** [comment]
thx

**Comment by tebeco** [comment]
Hello, @zpqrtbnk 
Any insight on this one ?
Also will be be ported to both 3.x and 4.x ?
We got few crash during `deployment` on this one, it kinda break `0 down time deployment` idea, has it cause an hard crash on the Application itself when we try to shut it down (eg: multiple deployment on ephemeral env like K8s or local development if the container it not ready on time)

**Comment by tebeco** [comment]
bumping it

**Comment by tebeco** [comment]
hello again ;)

**Comment by tebeco** [comment]
🏓

**Comment by zpqrtbnk** [comment]
Hey ;) v3 is now in maintenance mode and users are encouraged to move to v5. Are you stuck on v3?

**Comment by tebeco** [comment]
🤷im bot the one owning the board / jira / etc

i'm probably not supposed to close ticket

i'm just seeing that as part of bugs opened among all my github issue

i'm just reminding whoever how project that's there's dormant ticket

anyone with the authority to close a ticket officially in the name of hazelcast is free to close that ticket

**Comment by zpqrtbnk** [comment]
closing, then ;)
