### ISSUE TITLE
[QUESTION] Will Client v4.x be backward compatible with Cluster/Nodes in v3.x

### ISSUE THREAD

**Issue by tebeco** [hazelcast/hazelcast-csharp-client#288]
Hello,

As you may expect, updating all Nodes and Cluster might not always be done at the same pace in all environment / company.
Do you know if it will be possible to update `Hazelcast.Net` to v4.x while still connecting to a cluster in 3.x ?
If so, what would be the minimal version of the `Nodes` ?

That would allow us to update really fast the SDK, like for example 
* Be able to consumer the lib dealing with `async`
* Get ride of a homemade `IDistrubutedCache` implementation and use the official one
* all other goodness 

If so what would be the required minimal `v3.x` ? and what would be the recommended

**Comment by zpqrtbnk** [comment]
Hey,

Unfortunately, `Hazelcast.Net` v4.x will *not* be compatible with v3.x clusters, due to changes in the underlying communication protocols. The situation is the same with all clients (Python, Go...) including the native Java client.

Fortunately (somehow), the changes have been made to improve speed and efficiency. In addition, `Hazelcast.Net` is undergoing architecture changes at the moment, so that the v4.x version is natively asynchronous, more efficient, and generally speaking more "C#".

Happy to answer more questions!

**Comment by tebeco** [comment]
thanks for that clarification

how would you handle zero time deployment in an appliaction running 10 WebApi consuming a cluster in v3 ?

if i understand correctly i will need a new cluster
and all WebApi will now need to connect to the new one and so on
does this mean we would have to maintains 2 cluster and be REALLY sure both have the same state by the time all 10 webapi now know about v4

which also means to have multiple client (one per version) and feature flipping everywhere to write / read / ignore v4 or v3

is there a recommended easiest way for having no downtime ?

**Comment by zpqrtbnk** [comment]
v4 will come with a server-side migration tool that will let you run your current v3 cluster alongside a new v4 cluster, and they will remain in sync and have the same state. Once that is in place, you can start migrating your APIs (updating the clients) to v4, one by one. Once they are all running on v4, the (now old) v3 cluster can be shut down.

Note that the server-side migration tool is to be part of our Enterprise edition (along with WAN replication and rolling upgrades), and not available with the Open Source edition.

Making sense?

**Comment by tebeco** [comment]
yep totally makes sense,
We currently uses `Open Source` so no luck here, i totally understand that choice though, everything can't be free, especially such mitigation tool

Out of curiosity, 
The tool is running "inside / as a plugin" of the v4 cluster ?
an external process / same server (in process communication) ?
Or just rely on "Administration API" to hook on even on both side and contains 2 clients so synch state ?
(or is it "a secret" :D)
