### ISSUE TITLE
Shuffle members by default

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-csharp-client#290]
Unfortunately, the .NET client does not shuffle the list by default whereas java does by default. 

PS: Related prop is hazelcast.client.shuffle.member.list which is currently false in .NET client.

**Comment by burakcelebi** [comment]
Might be related: https://github.com/hazelcast/hazelcast-csharp-client/issues/165

**Comment by asimarslan** [comment]
fixed by #291
