### ISSUE TITLE
Build support for old/legacy environments

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast-csharp-client#307]
The build script and the project configurations have a dependency on net core 3.1.
As .Net Core SDK is an LTS and supported until 2021-08-21. Moreover, .Net framework is still in use.
We may consider support building only using one of the below versions 
* .Net Core SDK 2.1
* .NET Framework 4.6.2
* .NET Framework 4.7.2
* .NET Framework 4.8

**Comment by zpqrtbnk** [comment]
Samewise, the PowerShell build script fails when running on PowerShell 4.x and is untested on 5.0. It works on 5.1. And, we recommend people update to the latest (7.x at this time) version of PowerShell. We may want to support 4.x and/or better document what is happening here.

**Comment by emreyigit** [comment]
.Net framework 4.6 and 4.8 are supported. The others are out of support.
