### ISSUE TITLE
Hang for ever with Hazelcast 3.5

### ISSUE THREAD

**Issue by alexvictoor** [hazelcast/hazelcast-csharp-client#34]
Hello,
Thanks for having open sourced this csharp client.
I have done some testing and I have come to the conclusion that the current csharp client can only connect to an hazelcast cluster using a 3.6-RC snapshot version. Otherwise using Hazelcast 3.5, the client hangs for ever. 
Am I missing something?
Regards

**Comment by cangencer** [comment]
Yes this is correct. Hazelcast 3.6 is not backwards compatible with Hazelcast 3.5, this includes both Java and C# clients. We have a new client protocol with this version which will allow us to be backwards compatible between releases from this point forward.

**Comment by alexvictoor** [comment]
Thanks for your response
IMHO since 3.6 has not been released yet, the doc of the csharp client should mention this compatibility issue, it might save time for other users
