### ISSUE TITLE
Java to dotnet number serialization

### ISSUE THREAD

**Issue by alexvictoor** [hazelcast/hazelcast-csharp-client#35]
Hello
I have tried to share some data between a java process and a dotnet one using a map.
Using a key of type double on both side of Integer/Int32 , I get serialization errors on the dotnet side with the following message "There is no suitable de-serializer for type 0".
I guess this might be related to dotnet "struct" types. I could wrap my key in a IPortable class but this does not seems to be a memory efficient solution...
Let me know if I have missed something in the doc
Regards

**Comment by cangencer** [comment]
Are you using the same HZ RC version on both sides? The reason being there were some serialization changes between the EA releases and latest snapshots. You can try using the 3.6-EA2 Hazelcast releases. If you are still having issues, could you add some code demonstrating the problem you are experiencing?

**Comment by alexvictoor** [comment]
Well on the dotnet side I am using version 3.6.0-EA , the only one available on nuget.org .
On the java side I am using hazelcast-3.6-RC2-20151203.155725-88.jar .
Below the code I am using on the java side:

        HazelcastInstance instance = Hazelcast.newHazelcastInstance(cfg);
        Map<Integer, String> mapCustomers = instance.getMap("customers");
        mapCustomers.put(1, "Joe");
        mapCustomers.put(2, "Ali");
        mapCustomers.put(3, "Avi");

On the C# side:

       var client = HazelcastClient.NewHazelcastClient(config);
       var map = client.GetMap<Int32, string>("customers");
       var entries = map.EntrySet().AsEnumerable();
       foreach (var keyValuePair in entries)
       {
           Console.Out.WriteLine(keyValuePair.Key  + " " + keyValuePair.Value);
       }

Let me know if there is something else I can try

**Comment by cangencer** [comment]
Looks like the version on nuget is the previous EA version still. We will
have it updated, meanwhile you can download the latest EA from the website:
http://download.hazelcast.com/clients/3.6-EA2/hazelcast-csharp-client-3.6-EA2.zip

**Comment by alexvictoor** [comment]
Indeed this new version solves my problem!
Thanks! Hope it will be published soon.
