### ISSUE TITLE
Consider specializing the remote exceptions

### ISSUE THREAD

**Issue by zpqrtbnk** [hazelcast/hazelcast-csharp-client#363]
At the moment, everything that throws on the server becomes a `RemoteException` with an `Error` property that provides the error code returned by the server. Based upon this code, we may want to consider creating specialized exceptions?

For now we have to do:
```csharp
catch (RemoteException e) when (e.Error == RemoteError.QueryResultSizeExceeded)
{ ... }
```

We could do:
```csharp
catch (QueryResultSizeExceededException e)
{ ... }
```

Discuss: do we want this?

**Comment by burakcelebi** [comment]
Other clients have similar specialized exceptions. But, living with the generic one works too.

**Comment by zpqrtbnk** [comment]
Going to clean the backlog by removing this. Think it's perfectly fine, and easier to maintain, to have one unique exception.
