### ISSUE TITLE
AtomicLong, Lock, etc. in 4.0

### ISSUE THREAD

**Issue by andy-dev947** [hazelcast/hazelcast-csharp-client#369]
Hi,

I appreciate 4.0 is still under active development but I just wondered what the plan was for structures like AtomicLong, Lock, etc. that were available in 3.12.  Are these going to make it into the initial 4.0 release or will they come later because they need to be re-implemented using the CP subsystem?

**Comment by zpqrtbnk** [comment]
Hey,

You got it right, these structures will not be part of the original 4.0 release, but will make it into the 4.1 release with the re-implemented CP subsystem. 4.0 is "very soon" now, and 4.1 does not have a release date yet.

**Comment by zpqrtbnk** [comment]
Update: version 4.1, which has been [released](https://github.com/hazelcast/hazelcast-csharp-client/releases/tag/v4.1.0), implements `IAtomicReference`. Then, `IAtomicLong` has been implemented, and will be part of the next yet-to-be-released version. 

As for locks, they are available on maps (an entry can be mapped) and distributed locks remain in backlog.

**Comment by emreyigit** [comment]
AtomicLong and FencedLock are available >5.2.0
