### ISSUE TITLE
Hazlecast implementation of Microsoft.Extensions.Caching

### ISSUE THREAD

**Issue by MonDeveloper** [hazelcast/hazelcast-csharp-client#371]
Hi Hazlecast dotnet team!

There is room for an implementation of the `Microsoft.Extensions.Caching` made using Hazelcast?

Something similar to what have been done by these [packages](https://www.nuget.org/packages?q=Microsoft.Extensions.Caching)

**Comment by burakcelebi** [comment]
Hi @MonDeveloper! Yes, IDistributedCache implementation is one of the top items in our backlog. cc: @zpqrtbnk 

Please let us know if you are interested in contributing to the effort with our support :) 
__
[Join Hazelcast Community on Slack](https://slack.hazelcast.com)

**Comment by emreyigit** [comment]
It's available within 5.2.0.
