### ISSUE TITLE
Hanging on client creation

### ISSUE THREAD

**Issue by alexvictoor** [hazelcast/hazelcast-csharp-client#38]
Hello
If I start a dotnet client prior to any hazelcast node, then start an hazelcast instance, the client connects  but never completes the initialization and hangs forever.
The code used on the dotnet side:

            var config = new ClientConfig();
            config.GetNetworkConfig().AddAddress(new[] { "127.0.0.1:5701" });
            var client = HazelcastClient.NewHazelcastClient(config); // stay here for ever

To start an hazelcast instance I simply use the following command:

      start java -jar hazelcast-3.6-RC2-20151203.155725-88.jar

The logs that I get on the dotnet side:

    22:19:03.772 [FINEST] - [:8] Hazelcast.Client.Spi.ClientClusterService: Trying to connect to Address[127.0.0.1]:5701
    22:19:03.772 [FINEST] - [:8] Hazelcast.Client.Connection.IClientConnectionManager: Creating new connection for Address[127.0.0.1]:5701 with id 0
    22:19:03.784 [FINEST] - [:8] Hazelcast.Client.Spi.ClientClusterService: Authenticating against the owner node
    // nothing after that

Let me know if I have missed anything or if you need more information

**Comment by cangencer** [comment]
Hi Alex,

Are you using the same version of the client and the server? I just checked and the version on Nuget is not updated with the latest release candidate for 3.6.

**Comment by alexvictoor** [comment]
Thanks for the tip, I did not notice new versions were released 3 days ago.
I will do some testing and get back to you

**Comment by alexvictoor** [comment]
Hello again,
Running EA3 on both sides the behavior is a little bit different, call to HazelcastClient.NewHazelcastClient() raise an exception:

        System.InvalidOperationException was unhandled
          _HResult=-2146233079
          _message=Unable to connect to any address in the config! The following addresses were tried:127.0.0.1:5701
          HResult=-2146233079
          IsTransient=false
          Message=Unable to connect to any address in the config! The following addresses were tried:127.0.0.1:5701
          Source=Hazelcast.Net
          StackTrace:
               à Hazelcast.Client.Spi.ClientClusterService.ConnectToOne()
               à Hazelcast.Client.Spi.ClientClusterService.ConnectToCluster()
               à Hazelcast.Client.Spi.ClientClusterService.Start()
               à Hazelcast.Client.HazelcastClient.Start()
               à Hazelcast.Client.HazelcastClient.NewHazelcastClient(ClientConfig config)
               à HzSource.Program.Main(String[] args) dans c:\work\dotnetsandbox\HzSandbox\HzSource\Program.cs:ligne 24
               à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
               à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
               à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
               à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
               à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
               à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
               à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
               à System.Threading.ThreadHelper.ThreadStart()
          InnerException: 

On the hazelcast instance, I have also an exception:

                INFOS: [192.168.0.16]:5701 [dev] [3.6-EA3] Accepting socket connection from /127.0.0.1:49397
                dÚc. 26, 2015 11:01:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
                INFOS: [192.168.0.16]:5701 [dev] [3.6-EA3] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:49397
                dÚc. 26, 2015 11:01:55 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
                GRAVE: [192.168.0.16]:5701 [dev] [3.6-EA3] Hazelcast instance is not ready yet!
                com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not ready yet!
                        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:115)
                        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:96)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                        at java.lang.Thread.run(Unknown Source)
                        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
                        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

                dÚc. 26, 2015 11:01:55 PM com.hazelcast.nio.tcp.TcpIpConnection
                INFOS: [192.168.0.16]:5701 [dev] [3.6-EA3] Connection [/127.0.0.1:49397] lost. Reason: java.io.EOFException[Remote socket closed!]
                dÚc. 26, 2015 11:01:58 PM com.hazelcast.cluster.impl.MulticastJoiner
                INFOS: [192.168.0.16]:5701 [dev] [3.6-EA3]


                Members [1] {
                        Member [192.168.0.16]:5701 this
                }

                dÚc. 26, 2015 11:01:58 PM com.hazelcast.core.LifecycleService
                INFOS: [192.168.0.16]:5701 [dev] [3.6-EA3] Address[192.168.0.16]:5701 is STARTED

**Comment by alexvictoor** [comment]
I have set  the connection attempt limit and it seems to work fine now!
I did not notice that from EA2 to EA3 the default value of this limit went from 20 to 2.
Thanks for your help

**Comment by alexvictoor** [comment]
BTW why these new clients are not available thru nuget?
I am closing this issue since the issue is solved

**Comment by cangencer** [comment]
All the releases are published to nuget now, and also we have integrated it with our release process so they should be available simultaneously as actual releases. 

https://www.nuget.org/packages/Hazelcast.Net/3.6.0-EA3

**Comment by alexvictoor** [comment]
Thanks a lot!!!
FYI I have started to write a simple [SignalR integration](https://github.com/alexvictoor/SignalR-Hazelcast)

**Comment by cangencer** [comment]
That's great! Feel free to pop us any issues you might encounter with the client.
