### ISSUE TITLE
[TRACKING ISSUE] Send -1 instead Long.Max for leasetime by default

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-csharp-client#400]
The tracking issue for the Java side PR.

**Send -1 instead Long.Max for leasetime by default**

See https://github.com/hazelcast/hazelcast/pull/17676 for details.

---

fixes https://github.com/hazelcast/hazelcast/issues/17637

**Comment by emreyigit** [comment]
Already exist in the client.
