### ISSUE TITLE
Exceptions while sending messages on reconnection

### ISSUE THREAD

**Issue by alexvictoor** [hazelcast/hazelcast-csharp-client#42]
I have tried to test a failover scenario with hazelcast 3.6 and the csharp client (3.6 as well) and I think I might found a bug.
I have written a tiny csharp program that instantiate an hazelcast client that listens on a topic and send messages to the same topic within a loop. The client can connect to two different hazelcast instances. 
The test scenario is quite simple :
1. start a first hazelcast instance
2. start a second hazelcast instance
3. start the csharp client
4. shutdown the hazelcast instance which have the longest uptime and then wait a few seconds
5. start again an hazelcast instance
6. wait a few seconds and iterate to step 4

After a few iterations my csharp client crashes while trying to send messages while switching from one instance to the other one.

I have also written the very same program in java - I have not succeed to reproduce the issue with the java version.

Below my csharp code:

```
 static void Main(string[] args)
    {
        Environment.SetEnvironmentVariable("hazelcast.logging.level", "All");
        Environment.SetEnvironmentVariable("hazelcast.logging.type", "console");
        var config = new ClientConfig();
        config.GetNetworkConfig().SetConnectionAttemptLimit(10);
        config.GetNetworkConfig().AddAddress(new[] { "127.0.0.1:5701", "127.0.0.1:5702" });
        var client = HazelcastClient.NewHazelcastClient(config);
        var topic = client.GetTopic<string>("backplane");
        topic.AddMessageListener(msg => Console.Out.WriteLine("Received msg: " + msg.GetMessageObject()));
        IAtomicLong counter = client.GetAtomicLong("counter");
        for (int i = 0; i < 1000; i++)
        {
            var sqn = counter.IncrementAndGet();
            Console.Out.WriteLine("Hello " + i + " " + sqn);
            Thread.Sleep(1000);
            topic.Publish(i + " hello " + DateTime.Now);
        }
     }
```

I start my hazelcast instances with the default config - i.e. with the following command line:

```
  start java -jar hazelcast-3.6.jar
```

Below an exception stacktrace I have got with the scenario described above:

```
    Hazelcast.Client.Spi.TargetDisconnectedException was unhandled
      _HResult=-2146233087
      _message=Target[Address[192.168.0.15]:5701] disconnected.
      HResult=-2146233087
      IsTransient=false
      Message=Target[Address[192.168.0.15]:5701] disconnected.
      Source=Hazelcast.Net
      StackTrace:
           à Hazelcast.Client.Spi.ClientProxy.Invoke(IClientMessage request, Object key)
           à Hazelcast.Client.Proxy.ClientTopicProxy`1.Invoke(IClientMessage request)
           à Hazelcast.Client.Proxy.ClientTopicProxy`1.Publish(T message)
           à HzSource.Program.Main(String[] args) dans c:\work\dotnetsandbox\HzSandbox\HzSource\Program.cs:ligne 41
           à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
           à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
           à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
           à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
           à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           à System.Threading.ThreadHelper.ThreadStart()
      InnerException: 
```

Let me know if you need more details
Regards

**Comment by alexvictoor** [comment]
If I restart more quickly an hazelcast instance, I get a different exception:

          Hazelcast.Core.HazelcastException was unhandled
            _HResult=-2146233087
            _message=Hazelcast instance is not active!
            HResult=-2146233087
            IsTransient=false
            Message=Hazelcast instance is not active!
            Source=Hazelcast.Net
            StackTrace:
                 à Hazelcast.Client.Spi.ClientProxy.Invoke(IClientMessage request, Object key)
                 à Hazelcast.Client.Proxy.ClientTopicProxy`1.Invoke(IClientMessage request)
                 à Hazelcast.Client.Proxy.ClientTopicProxy`1.Publish(T message)
                 à HzSource.Program.Main(String[] args) dans c:\work\dotnetsandbox\HzSandbox\HzSource\Program.cs:ligne 41
                 à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
                 à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
                 à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
                 à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
                 à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                 à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                 à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                 à System.Threading.ThreadHelper.ThreadStart()
            InnerException:

**Comment by cangencer** [comment]
Sorry for the late response. Upon a first investigation, it looks like TargetDisconnectedException is not retried automatically, but perhaps it should be. The problem seems not to appear if you set `config.GetNetworkConfig().SetRedoOperation(true)`, as this will retry when TargetDisconnectedException is thrown. A different exception is thrown in the Java client in this case, so the issue does not appear.

**Comment by alexvictoor** [comment]
Thanks for your answer
With SetRedoOperation I do not get TargetDisconnectedException anymore, however I get other weird behaviors running the same scenario several times. I have managed to be in a state where one client succeed to reconnect whereas another one dit not. In the logs I have just got the following lines and then nothing:

    22:03:23.829 [WARNING] - [:28] Hazelcast.Client.Connection.ClientConnection: Got socket error:   -1073741299
    22:03:23.861 [INFO] - [:22] Hazelcast.Core.ILifecycleService: HazelcastClient[hz.client_0_dev] is   ClientDisconnected
    22:03:23.985 [INFO] - [:22] Hazelcast.Core.ILifecycleService: HazelcastClient[hz.client_0_dev] is     ClientConnected
    22:03:27.565 [INFO] - [hz-striped-scheduler-0:9] Hazelcast.Client.Spi.ClientMembershipListener:

    Members [1] {
             IMember [192.168.0.15]:5702
    } 
  
I will try to do more testing to give you more details.

**Comment by emreyigit** [comment]
Closed due to expire and incompatibility between 3.x and 4.x
