### ISSUE TITLE
Read/WriteObject in SerializationService non-compliant with Java equivalents

### ISSUE THREAD

**Issue by ph33rtehgd** [hazelcast/hazelcast-csharp-client#43]
The ReadObject and WriteObject methods within the SerializationService class perform a null check on the object in question by either doing a ReadBoolean to determine if the object is null or a WriteBoolean to record the object as null. 

**ReadObject (C#)**

```
try
            {
                var isNull = input.ReadBoolean();
                if (isNull)
                {
                    return default(T);
                }
....
```

**WriteObject (C#)**
```
var isNull = obj == null;
            try
            {
                output.WriteBoolean(isNull);
                if (isNull)
                {
                    return;
                }
                var serializer = SerializerFor(obj);
                output.WriteInt(serializer.GetTypeId());
                serializer.Write(output, obj);
            }
            catch (Exception e)
            {
                throw HandleException(e);
            }
```

The Java equivalents readObject and writeObject in the AbstractSerializationService class do not read or write any boolean from the stream to check for "nullness". The result of this is that any stream that utilizes these methods will fail because the C# client reads/writes one extra byte (for the "nullness" boolean). This causes reading and writing to fail. ~~A quick check on the audit of both serialization service classes shows that the C# client has always done this and the Java equivalent hasn't done this, meaning these methods would have never worked~~. Updated: According to @cangencer this was changed in 3.5.5. I'm very new to Hazelcast (and C#/.NET itself) as well as Github (go easy on me :)), but can anyone confirm that my findings are indeed an issue? Removing these read/write boolean calls allows me to utilizes these methods.

Here are the Java equivalents to the above:

**readObject**
```
public final <T> T readObject(final ObjectDataInput in) {  
        try {  
            final int typeId = in.readInt();  
            final SerializerAdapter serializer = serializerFor(typeId);  
            if (serializer == null) {  
                if (active) {
                    throw newHazelcastSerializationException(typeId);
                }
                throw new HazelcastInstanceNotActiveException();
            }
            Object obj = serializer.read(in);
            if (managedContext != null) {
                obj = managedContext.initialize(obj);
            }
            return (T) obj;
        } catch (Throwable e) {
            throw handleException(e);
        }
    }
```

**writeObject**
```
@Override
    public final void writeObject(final ObjectDataOutput out, final Object obj) {
        if (obj instanceof Data) {
            throw new HazelcastSerializationException(
                    "Cannot write a Data instance! " + "Use #writeData(ObjectDataOutput out, Data data) instead.");
        }
        try {
            SerializerAdapter serializer = serializerFor(obj);
            out.writeInt(serializer.getTypeId());
            serializer.write(out, obj);
        } catch (Throwable e) {
            throw handleException(e);
        }
    }
```

**Comment by cangencer** [comment]
Looks like this behaviour was changed from 3.5.5 Java Client, but never updated in the C# client. @asimarslan can you confirm?

**Comment by ph33rtehgd** [comment]
Thanks @cangencer! I did a little more digging into the sources of the older versions of Hazelcast, and I see that 3.5.5 still has the "nullness" boolean being written, but starting with 3.6-EA this is no longer done. The reason I didn't see this from the Java client's history was because the class doing the serialization was called something different and was in a different package (was previously in com.hazelcast.nio.serialization.SerializationServiceImpl).
