### ISSUE TITLE
Hazelcast.Net.Win32

### ISSUE THREAD

**Issue by andy-dev947** [hazelcast/hazelcast-csharp-client#431]
Hi,

Are there any plans to distribute this via nuget so we can use kerberos integration?

Thanks,

**Comment by zpqrtbnk** [comment]
Yes, in a near future. We are currently validating that it all works.

**Comment by zpqrtbnk** [comment]
Package v4.0.1 now available on NuGet.

**Comment by andy-dev947** [comment]
Hi,

I installed this package but am not sure if there is something wrong with the public key signing:

```
<Reference Include="Hazelcast.Net, Version=4.0.1.0, Culture=neutral, PublicKeyToken=696d29173d68bfe5, processorArchitecture=MSIL">
      <HintPath>..\packages\Hazelcast.Net.4.0.1\lib\netstandard2.0\Hazelcast.Net.dll</HintPath>
    </Reference>
    <Reference Include="Hazelcast.Net.Win32, Version=4.0.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Hazelcast.Net.Win32.4.0.1\lib\netstandard2.0\Hazelcast.Net.Win32.dll</HintPath>
    </Reference>
```

Is it correct that Hazelcast.Net.Win32 isn't signed?

**Comment by zpqrtbnk** [comment]
No. Should be signed just like other packages. Can you open a new issue to track this, and I'll have a look ASAP.
