### ISSUE TITLE
Hazelcast.Net.Win32 public key issue

### ISSUE THREAD

**Issue by andy-dev947** [hazelcast/hazelcast-csharp-client#456]
Hi,

It seems that the Hazelcast.Net.Win32 assembly in the nuget package is not signed correctly so you get the following error when trying to use it

```
FileLoadException: Could not load file or assembly 'Hazelcast.Net, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Steps to reproduce:

Create a new .NET 4.7 Console app
Install Hazelcast.Net 4.0.1 from nuget
Install Hazelcast.Net.Win32 4.0.1 from nuget

Attempt to connect to a cluster using 

```
await HazelcastClientFactory.StartNewClientAsync(options =>
{
	options.Networking.Addresses.Add("localhost:5701");
	options.Authentication.ConfigureKerberosCredentials("spn");
});
```

In the proj file I see:

```
<Reference Include="Hazelcast.Net, Version=4.0.1.0, Culture=neutral, PublicKeyToken=696d29173d68bfe5, processorArchitecture=MSIL">
      <HintPath>..\packages\Hazelcast.Net.4.0.1\lib\netstandard2.0\Hazelcast.Net.dll</HintPath>
    </Reference>
    <Reference Include="Hazelcast.Net.Win32, Version=4.0.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Hazelcast.Net.Win32.4.0.1\lib\netstandard2.0\Hazelcast.Net.Win32.dll</HintPath>
    </Reference>
```

**Comment by zpqrtbnk** [comment]
Downloaded the package from NuGet and verified it with [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer), got report:

* Source Link: Has Symbols, **No Source Link**
* Deterministic (dll/exe): **Non deterministic**
* Strong Name: **No**

This confirms the issue. Investigating.

**Comment by zpqrtbnk** [comment]
Fixed by PR and rebuild, cannot "re-push" version 4.0.1 to NuGet, will push next version (4.0.2) soon.
