### ISSUE TITLE
Dll hell

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#469]
We're running into an issue consuming the Hazelcast .NET client in an ASP.NET WCF web services application.
I'm still digging to find what the exact cause is, but one of the things we noticed is that different components used by the Hazelcast  client expect different versions of **System.Runtime.CompilerServices.Unsafe**.

All components (assemblies) were compiled against version **4.0.4.1** of **System.Runtime.CompilerServices.Unsafe**, except for **Microsoft.Extensions.Primitives**. The latter was compiled against version **5.0.0.0** of **System.Runtime.CompilerServices.Unsafe**.

A brief summary:

Assembly|Depends on version of ...Unsafe|
----------|---------------------|
|System.Memory|4.0.4.1|
|System.Threading.Tasks.Extensions|4.0.4.1|
|Microsoft.Extensions.Primitives|5.0.0.0|

The dependency on **Microsoft.Extensions.Primitives** comes from **Microsoft.Extensions.Configuration.Json** which in turns references a few other assemblies that in turn depend on version **5.0.0.0** of **System.Runtime.CompilerServices.Unsafe**.

We can of course work around this using assembly binding redirects, but I thought it was interesting information nonetheless as it may explain our issue in the ASP.NET WCF web service application since this is our only application in which we effectively had to add the assembly binding redirect.

All our other applications also target .NET Framework 4.7.2 so they all use the same target framework version of Hazelcast (and its dependencies).

**Comment by drieseng** [comment]
@zpqrtbnk I'll keep digging to find the cause of the problem we have in the ASP.NET WCF web services application (and open a new issue if/when I have more info), but do you think this issue is one of the possible causes?

**Comment by zpqrtbnk** [comment]
I somehow missed this issue. Going to look into it.

**Comment by zpqrtbnk** [comment]
OK, I am not *actually* looking into it. IIC we have

Microsoft.Extensions.Configuration.Json 
🡢 (assemblies) 
🡢 Microsoft.Extensions.Primitives 
🡢 System.Runtime.CompilerServices.Unsafe version **5.0.0**

whereas other dependencies want version 4.x of that library.

And there's a similar situation with System.Buffers.

I *think* we should provide a NuGet package that does not require binding redirects, probably by up/downgrading some of our packages. Working on it.

**Comment by zpqrtbnk** [comment]
>I think we should provide a NuGet package that does not require binding redirects, probably by up/downgrading some of our packages. Working on it.

Well, I really tried. But the whole .NET Framework situation is a mess. We would need to downgrade a wide range of packages and even then, some conflicts remain. So, we are definitively going to recommend that people run with binding redirects. You'll need to redirect:
* `System.Buffers`  --  usual troublemaker
* `System.Runtime.CompilerServices.Unsafe`  --  usual troublemaker
* `Microsoft.Bcl.AsyncInterfaces`  -- only if you're using `System.Linq.Async` (e.g. our examples)

You can enable `<AutoGenerateBindingRedirects>` in your project file, and it should/may generate all the required binding redirects. Or, manually:
```xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
  </dependentAssembly>
</assemblyBinding>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
   <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
  </dependentAssembly>
</assemblyBinding>
```

**Next**: I am going to update our documentation accordingly.

And, two things:
* Looking into adding an assembly scan in our build pipeline to detect required redirects - so the doc is always updated
* Looking into detecting the situation and producing a nice/detailed error
