### ISSUE TITLE
Guidance on usage in long-running service

### ISSUE THREAD

**Issue by GaTechThomas** [hazelcast/hazelcast-csharp-client#484]
The provided examples are very helpful to show basic usage. For usage in long-lived processes, what is the guidance on creation/initialization?...

Should StartNewClientAsync be called once and reused for the life of the service? Or should it be called repeatedly as needed?

Same two questions for the results of GetSetAsync. (And any other similar objects.)

**Comment by zpqrtbnk** [comment]
Starting a new client, especially in *Smart Client* mode (where the client connects to each member of the cluster) with a number of members, can be a somewhat expensive operation. The `IHazelcastClient` is multi-threaded and supposed to be long-lived. In other words: if you can, create one unique client and re-use it for the life of your service.

Note that you may want to set the `HazelcastOptions.Networking.ReconnectMode` to `ReconnectAsync` to ensure that, should the connection between the client and the cluster dies, the client reconnects (as soon as it can).

As for distributed objects such as `IHSet` which you obtain with `GetSetAsync(...)`, these are cheap-enough objects (memory-wise) to keep around, so you probably want to keep them long-live too. However, the cost of "getting" one such object is only one remote operation to the cluster, so it is not as important as for clients. I would advise against repeatedly and frequently getting them, though.

What can I add to this answer to make you fully satisfied?

**Comment by GaTechThomas** [comment]
This is super helpful. To answer your question, the best answer would be one that writes our code for us, but that's just silly. However, any real-world reference solution code would be very useful.

**Comment by GaTechThomas** [comment]
I should apologize... I did not RTFM. Now that I've found the, er, "FM", it is answering the questions that I had. Thank you for your answer and sorry to waste your time.

**Comment by zpqrtbnk** [comment]
Also, the "FM" is not always as "F" as we would like it to be ;) But it's getting better.
