### ISSUE TITLE
Repository website link is incorrect

### ISSUE THREAD

**Issue by seii** [hazelcast/hazelcast-csharp-client#491]
Currently the website link for this repo is shown as `https://hazelcast.com/clients/net/`, but that leads to an error page. The correct link is `https://hazelcast.com/clients/dotnet/`.

**Comment by alexb5dh** [comment]
Hi @seii, could you please clarify which website incorrect link is located at? One at https://hazelcast.com/clients/ seems correct.

**Comment by seii** [comment]
I mean the link here on GitHub for the repository itself. Screenshot below:

![image](https://user-images.githubusercontent.com/8258251/129742611-75929a81-5ed0-4702-88e8-336d42478f20.png)

**Comment by alexb5dh** [comment]
Fixed, thank you for noticing!
