### ISSUE TITLE
HMap EntryRemoved events do not include the OldValue

### ISSUE THREAD

**Issue by osmedd** [hazelcast/hazelcast-csharp-client#501]
When subscribing to EntryRemoved events for an HMap (for example as in the MapEventsExample), I do not see the OldValue being populated in the event args.  This does work for EntryUpdated events and did work in the 3.x .NET client.

I am using the 4.1.0 client and tested against the 4.2.1 server as well as a 5.0 snapshot server.

Help?

**Comment by zpqrtbnk** [comment]
Not 100% sure yet but probably reproduced. Stay tuned.

**Comment by zpqrtbnk** [comment]
Confirmed, going to push a PR.
