### ISSUE TITLE
Invalid Hazelcast URL causes client to hang and allocate infinite memory [API-1027]

### ISSUE THREAD

**Issue by Eragra3** [hazelcast/hazelcast-csharp-client#530]
Hello everybody 🙃,

recently we started using your library, it works very well in our scenarios.

However, we just discovered very problematic behavior when Hazelcast client receives invalid configuration -
in this case invalid Hazelcast server url.

When, for instance, you put a space before hazelcast url (or provide url that does not host Hazelcast):
```json
{
  "hazelcast": {
    "clusterName": "dev",
    "networking": {
      "addresses": [
        " localhost"
      ]
    }
  }
}
```
Hazelcast client will fall in a loop of reconnecting.

First problem is looping over obviously invalid config, I think on exceptions like `System.FormatException` - `The string " localhost" does not represent a valid network address`, the client should immediately throw. It's impossible that the url suddenly became valid.

Second, bigger problem, is the fact that for some reason `ClusterConnections` class is saving all exceptions to a list.
I understand that was supposed to aggregate exceptions over different addresses, but what happens is when you provide Hazelcast url that the client can't connect to - you will use up all memory and kill the entire host machine.

`ClusterConnections` indefinitely allocates more and more exceptions and keeps them inside a list that never gets GC'ed.

I copied the method causing the issue, removed some code (marked with `(...)`) and stripped original comments.
I added my own comments, maybe it will help a little bit to understand what happens.

The class is : `Hazelcast.Clustering.ClusterConnections.ConnectFirstAsync`
```C#
        private async Task ConnectFirstAsync(CancellationToken cancellationToken)
        {
            var tried = new HashSet<NetworkAddress>();
            List<Exception> exceptions = null; // This variable causes a sort of memory leak, it will grow infinitly
            bool canRetry;

            _connectRetryStrategy.Restart();

            do
            {
                try
                {
                    foreach (var address in GetClusterAddresses())
                    {
                        //(...)
                        var attempt = await ConnectFirstAsync(address, cancellationToken).CfAwait();

                        if (attempt)
                        {
                            //(...)
                            return; // Successful exit, a first connection has been opened. This works fine
                        }

                        HConsole.WriteLine(this, $"Failed to connect to address {address}");

                        if (attempt.HasException)
                        {
                            exceptions ??= new List<Exception>();
                            exceptions.Add(attempt.Exception); // !!! Save this exception for... no reason?

                            _logger.LogDebug(attempt.Exception, "Connection attempt has thrown.");
                        }
                    }
                }
                catch (Exception e)
                {
                    exceptions ??= new List<Exception>();
                    exceptions.Add(e); // !!! Save this exception for... no reason?

                    _logger.LogDebug(e, "Connection attempt has thrown.");
                }

                try
                {
                    canRetry = await _connectRetryStrategy.WaitAsync(cancellationToken).CfAwait(); // Always returns `true`
                }
                catch (OperationCanceledException)
                {
                    canRetry = false;
                }
                catch (Exception e)
                {
                    exceptions ??= new List<Exception>();
                    exceptions.Add(e);
                    canRetry = false;
                }

            } while (canRetry); // !!! `canRetry` is always true

            var aggregate = new AggregateException(exceptions); // This code is never called

            //(...)
            //throw aggregate exception
        }
```

I think this issue can be partially resolved by setting a connection timeout.

I don't know if you were aware of this issue, but before doing any PRs I wanted to ask if you prefer any solution. This isn't maybe a blocker, but it's a significant problem. Providing invalid configuration kills our entire web farm and we have to restart machines/kill processes to revive them.

Can we either:
1. Set connection timeout to be finite by default again
2. Add an option to provide custom `IRetryStrategy` that is finite
3. Fix the class so it won't memorize the exceptions

Thanks for reading!

Kind regards
Daniel

**Comment by zpqrtbnk** [comment]
There are various things here:
1. `" localhost"` (with a leading space) should parse to a valid address. I need to look into our parser to figure out why it fails.
2. Decision was made to make connection timeout infinite to align with our other clients. This has already caused various issues where connections that should fail and crash the app hang forever. We need to reconsider this decision.
3. The retry strategy _can_ be made to timeout via the `options.Networking.ConnectionRetry.ClusterConnectionTimeoutMilliseconds` but that should be better documented (and again, probably not infinite by default).
4. The memory leak is a nasty issue. In _theory_ we want the exceptions to be caught, stored, and reported if connection fails. That is, if the _application_ eventually fails. But if the timeout is infinite, the exceptions would never ever be reported, hence the leak. We need to (a) not store exceptions when the timeout is infinite and (b) probably only store the N latest exceptions.

I _think_ that setting a timeout could be an immediate workaround for your issue?

As for the rest: will look into fixes soon.
