### ISSUE TITLE
Share IHazelcastClient across requests

### ISSUE THREAD

**Issue by thomkinson** [hazelcast/hazelcast-csharp-client#538]
Hi,

In previous example of the hazelcast client, we were able to register a Singleton in DI so that is shared across multiple requests. We did not want to open multiple connections to the Hazelcast server, as it was capable of handling as many requests.

Upgrading to the latest version, I could not find how we could register a single IHazelcastClient to share across our services. Each Hazelcast example always created a new client using HazelcastClientFactory.StartNewClientAsync().

Is there a way to register a Singleton to only use a single IHazelcastClient?
Have you noticed any performance issues always starting a new Client?

**Comment by zpqrtbnk** [comment]
Hi,

You may want to have a look at [this documentation page](https://hazelcast.github.io/hazelcast-csharp-client/latest/doc/configuration/sources.html) and include our [Hazelcast.Net.DependencyInjection[(https://www.nuget.org/packages/Hazelcast.Net.DependencyInjection/) NuGet package in your solution. It handles everything related to configuration, and from there registering a singleton clients should not be too difficult (but ask if it's not simple enough and we'll update the docs).

The examples always create new clients, to avoid introducing DI complexity when not relevant. However, the `ContainerExample` (see [ContainerExample.cs](https://github.com/hazelcast/hazelcast-csharp-client/blob/master/src/Hazelcast.Net.Examples/Client/ContainerExample.cs)] does pretty much what you are trying to do IIC.

**Comment by thomkinson** [comment]
I saw that ContainerExample.cs. It is close to what I am after, I can work with that.  

Thanks for your reply
