### ISSUE TITLE
Logging improvements on .NET Client

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-csharp-client#56]
This is what we do on the server. We need to provide the same level of version information on the clients.

_INFO: [10.0.0.2]:5701 [dev] [3.6-EA2] Hazelcast 3.6-EA2 (20151125 - 8af85c5) starting at Address[10.0.0.2]:5701_
- 3.6-EA2 is the version.
- Hazelcast 3.6-EA2 is the full name
- 20151125 is the release date
- 8af85c5 is the GitHub Id.

See https://github.com/hazelcast/hazelcast/releases. You will see it corresponds to EA2

**Comment by cangencer** [comment]
Java PR: https://github.com/hazelcast/hazelcast/pull/7521

**Comment by cangencer** [comment]
Logging should also include the Hazelcast client instance name.

**Comment by zpqrtbnk** [comment]
version 4.0 currently reports
```
Authenticated client "hz.client_1" (8eb5391) with cluster "dev" member d333ab7 running version 4.0 at 127.0.0.1:5701 via 127.0.0.1:37480.
```
when a client connection authenticates on a member - where "4.0" is the version we receive from the server, so I assume we'd received "4.0-WHATEVER" if that was what the server was running. OTOH the server does *not* send the release date nor the release GitHub SHA for us to report.

We *may* want to report the client's version too - looking into it.

**Comment by zpqrtbnk** [comment]
Notes: reviewing other clients, we have

C++:
```
08/12/2020 20:19:09.802 INFO: [0x11427edc0] hz.client_1[little-endian-cluster] [4.0-SNAPSHOT] 
[../hazelcast/src/hazelcast/client/spi.cpp:379] (Mon Nov 30 16:35:50 2020 +0300:503c66fdf0) 
LifecycleService::LifecycleEvent Client (9f0cab3a-ea09-4c03-b964-97fd3e9bc632) is STARTING
```

Java:
```
INFO: [localhost]:5701 [dev] [4.1] Received auth from Connection[id=1, 
/127.0.0.1:5701->/127.0.0.1:55769, qualifier=null, endpoint=[127.0.0.1]:55769, alive=true,
connectionType=CPP, planeIndex=-1], successfully authenticated, clientUuid: 
3ff2c70c-6f1b-49a6-b07f-f5e63313a323, client version: 4.0-SNAPSHOT
```

**Comment by zpqrtbnk** [comment]
Proposing the following for C#:
```
info: Hazelcast.Clustering.ClusterConnections[0]
      Auth. client 'hz.client_1' (e3e1906) version 4.0.0-preview.3+97c7c0 connection 4c49ce3 
      127.0.0.1:1855 -> 127.0.0.1:5701 cluster 'dev' version 4.0 member d333ab7.
```
