### ISSUE TITLE
Usage guidelines

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#586]
I'm sure this is not the right channel for this type of question, but I'll give it a go anyway....

In the context of a multi-threaded application (as if there are other applications nowadays), do you recommend:
* using a single(ton) instance of **IHazelcastClient**
* using a single(ton) instance of a map (**IHMap<TKey, TValue>**)

**Comment by zpqrtbnk** [comment]
This may be ideally discussed on our [Hazelcast Slack Community](https://hazelcastcommunity.slack.com/) `dotnet-client` channel. Or maybe even a more general channel, as the question is common to all clients. Our clients are multi-threaded and each client (or map...) consumes resources, so the initial answer would be "just use one of each". And keep them around, as establishing a new client or a new map takes time, however optimized it can be. But there may be server-side considerations that escape my knowledge. So, yes, better ask on Slack.
