### ISSUE TITLE
.NET Standard 2.0 Support

### ISSUE THREAD

**Issue by manchuwook** [hazelcast/hazelcast-csharp-client#62]
[CoreCLR cross-platform](http://dotnet.github.io/)

Are there plans to support this?  It would be awesome to use Hazelcast with Windows IoT for distributed computing.  I've pulled down a Git copy of it, but it is a lot of stuff for me to learn and then convert over.

**Comment by cangencer** [comment]
The client has minimum dependencies so it should definitely be possible to use it on other platforms. Have you tried scanning the assembly with ApiPort tool developed by Microsoft? https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b

**Comment by gAmUssA** [comment]
@manchuwook I didn't have any problems to use Hazelcast C# client with mono on mac.

**Comment by Kantuz001** [comment]
+
we need to use hazelcast with dotnet core, not with .Net Framework

**Comment by Kantuz001** [comment]
https://github.com/hazelcast/hazelcast-csharp-client/pull/148

**Comment by asimarslan** [comment]
fixed by #148
