### ISSUE TITLE
StartNewClientAsync blocks indefinitely when (initial) connection cannot be established

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#632]
If the Hazelcast IMDG instance to which you connect is not available/running, then a call to `HazelcastClientFactory.StartNewClientAsync(HazelcastOptions options, CancellationToken cancellationToken = default)` will block indefinitely.

To reproduce, compile and run the following code (adding a reference to **Hazelcast.Net** version **4.0.2** or higher):

```cs
using System.Diagnostics;
using Hazelcast;

class Program
{
    private const string listenAddress = "localhost:5701";

    static async Task Main()
    {
        var sw = Stopwatch.StartNew();

        try
        {
            await CreateClient().ConfigureAwait(false);
            await Console.Error.WriteLineAsync($"Connected should have failed. Make sure Hazelcast IMDB is NOT running on '{listenAddress}'.");
        }
        catch (Exception e)
        {
            await Console.Out.WriteLineAsync(e.Message);
            await Console.Out.WriteLineAsync($"Elapsed time: {sw.ElapsedMilliseconds:D} ms");
        }
    }

    private static async Task<IHazelcastClient> CreateClient()
    {
        var options = new HazelcastOptionsBuilder().With((_, o) =>
                                                       {
                                                           o.Networking.Addresses.Add(listenAddress);
                                                           o.Networking.ConnectionTimeoutMilliseconds = 5000;
                                                           o.Networking.SmartRouting = false;
                                                       })
                                                   .Build();

        return await HazelcastClientFactory.StartNewClientAsync(options).ConfigureAwait(false);
    }
}
```

### Expected result:

The following output is written to stdout:

```
Unable to connect to the cluster "dev". The following addresses where tried: 127.0.0.1:5701.
Elapsed time: 5xxx ms
```

### Actual result:

The application blocks indefinitely.
This is a change in behavior that was introduced in version **4.0.2**.

### Notes

1. Even with **4.0.1**, the elapsed time before the exception is thrown is around **2000 ms**.
I would expect the elapsed time to be around **5000 ms** as that is the value I specified for **ConnectionTimeoutMilliseconds**.

2. I know you can configure **HazelcastOptions.Networking.ConnectionRetry.ClusterConnectionTimeoutMilliseconds** as a workaround, but I find this counter-intuitively: I expect a connection retry mechanism to only apply when you initially established a connection, and that connection dropped at some point.

3. `HazelcastClientFactory.StartNewClientAsync(HazelcastOptions options, CancellationToken cancellationToken = default)` also blocks indefinitely when:
* **HazelcastOptions.Preview.EnableNewReconnectOptions** is **true** and **HazelcastOptions.Preview.EnableNewReconnectOptions** is **false**.
-or-
* **HazelcastOptions.Preview.EnableNewReconnectOptions** is **false** and **HazelcastOptions.Networking.ReconnectMode** is **ReconnectMode.DoNotReconnect**.

I would not expect any reconnect mechanism to be active when these options are set.
Should I submit a separate issue for this?

**Comment by drieseng** [comment]
@emreyigit I don't mind the breaking change. I detected it early on, so no problem there. I suggest to clearly document this so others do not run into this (in production).

Feel free to close this issue.

**Comment by emreyigit** [comment]
@drieseng sure, appreciated for your feedback :)
