### ISSUE TITLE
ConfigureAwait missing on CancellationTokenRegistration [API-1401]

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#642]
In `MemberConnection.SendAsyncInternal(Invocation invocation, CancellationToken cancellationToken)`, the `ConfigureAwait(false)` is missing on the **CancellationTokenRegistration** returned by `CancelationToken.Register(...)`.

I propose to update [the code](https://github.com/hazelcast/hazelcast-csharp-client/blob/4345adb5437581af244dbba97a1185adc9c7a47b/src/Hazelcast.Net/Clustering/MemberConnection.cs#L451) as follows:
```cs
#if !NETSTANDARD2_0
                await
#endif
                using var reg = cancellationToken.Register(invocation.TrySetCanceled)
#if !NETSTANDARD2_0
                .ConfigureAwait(false)
#endif
                ;
```

or 

```cs
#if !NETSTANDARD2_0
                await using var reg = cancellationToken.Register(invocation.TrySetCanceled).ConfigureAwait(false);
#else
                using var reg = cancellationToken.Register(invocation.TrySetCanceled);
#endif
```

**Comment by zpqrtbnk** [comment]
Notes: 

Concerns versions up to and including *5.1.0*.

`await using var x = GetAsyncDisposable().ConfigureAwait(false);` configures how `await` on the task returned by the `IAsyncDisposable` when async-disposed is performed. This applies to all `await using` usage and has probably been overlooked in our codebase. Requires verification of all `await using` usages.

But note that `x` here is not the object returned by `GetAsyncDisposable()` but a `ConfiguredAsyncDisposable` instance, so the returned object is not available in the rest of the code. Also note that, should the producer of the `IAsyncDisposable` be an async method, a *double* `ConfigureAwait` is required: one for the method, and one for disposing.

The pattern to use ends up being:

```csharp
var x = await GetAsyncDisposableAsync().ConfigureAwait(false);
await using (x.ConfigureAwait(false))
{
    await x.RunAsync().ConfigureAwait(false);
}
```

Or

```csharp
var x = await GetAsyncDisposableAsync().ConfigureAwait(false);
await using var xd = x.ConfigureAwait(false);
await x.RunAsync().ConfigureAwait(false);
```

See [this C# language repo discussion](https://github.com/dotnet/csharplang/discussions/2661) for discussions and ideas, including an extension method that would allow the ugly one-liner below.

```csharp
// name AsAsyncDisposable = CfAwaitUsing to be consistent with our codebase?
await using var xd = (await GetAsyncDisposableAsync().ConfigureAwait(false)).AsAsyncDisposable(out var x);
await x.RunAsync().ConfigureAwait(false);
```
