### ISSUE TITLE
Breaking change introduced by #506 [API-1399]

### ISSUE THREAD

**Issue by drieseng** [hazelcast/hazelcast-csharp-client#643]
A breaking change wrt **Guid** serialization was introduced as part of #506.
Unless I'm mistaken, this was not documented as a (huge) breaking change.
Please make sure to clearly document such changes for future releases.

**Comment by drieseng** [comment]
@zpqrtbnk I'm asking you to revert this change. I lost some time with this, but I surely would've lost much more time if the project wasn't open-source. No need to say sorry for this.

I only created this issue so you can add information to the release notes, and make sure others do not run into the same issue.

**Comment by zpqrtbnk** [comment]
You write:
> I'm asking you to revert this change.

And then:
> I only created this issue so you can add information to the release notes.

And now you are getting me confused :) Is it OK to only update the release notes?

**Comment by drieseng** [comment]
> I'm asking you to revert this change.

The **not** word was missing in action. Sorry, I wrote it in a hurry.

> Is it OK to only update the release notes?

Yes, of course.

**Comment by zpqrtbnk** [comment]
A warning block has been added to the [release notes](https://github.com/hazelcast/hazelcast-csharp-client/releases/tag/v5.0.0).
