### ISSUE TITLE
CountDownLatch

### ISSUE THREAD

**Issue by kevindqc** [hazelcast/hazelcast-csharp-client#647]
We want to upgrade the Hazelcast .NET library in our project - we were using 3.12.1 - but CountDownLatch seems gone?

**Comment by emreyigit** [comment]
Hey, AFAIK, `CountDownLatch` is never been released. Could you be built from `master`?

**Comment by kevindqc** [comment]
I'm using the packages on NuGet.

3.12.1 has `CountDownLatch`, we wanted to upgrade to the latest version but `CountDownLatch` is gone.

![image](https://user-images.githubusercontent.com/228313/177186742-ad7e39f8-e104-4a56-b2d2-4c6f705909e2.png)

**Comment by emreyigit** [comment]
Okay, this is the situation. That `CountDownLatch` was not good enough and reliable. To overcome that [CP Subsystem](https://docs.hazelcast.com/hazelcast/5.1/cp-subsystem/cp-subsystem#hide-nav) is introduced, and `CountDownLatch` is reimplemented with CP Subsystem. However, .Net Client has not implemented it yet. Also, there a breaking changes with `v4.0`. `4.0` is not backward compatible, needs a [migration](http://hazelcast.github.io/hazelcast-csharp-client/latest/doc/migratingFrom3.html). If you demand the feature, you can open an issue. I'm sure that it will be considered and planned on the roadmap.
