### ISSUE TITLE
Missing "GetDistributedObjects()" function [API-1916]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-csharp-client#799]
On C# 5.2.0,
https://hazelcast.github.io/hazelcast-csharp-client/5.2.0/api/Hazelcast.IHazelcastClient.html
there is no way to list the distributed objects in the system

`GetDistributedObjects()` or similar

**Comment by mdumandag** [comment]
closing this as it is done in https://github.com/hazelcast/hazelcast-csharp-client/pull/805
