### ISSUE TITLE
ReliableTopic [API-1958]

### ISSUE THREAD

**Issue by vladimir-mocanu-ceia** [hazelcast/hazelcast-csharp-client#91]
Is ReliableTopic in the plans for this client? If yes, approximately when? Cheers!

**Comment by thinkSharp** [comment]
Reliable topic feature is one of the needed feature for us integrating Hazelcast with our system, I hope that this feature is included in 3.10

**Comment by dmartinsid** [comment]
I need this feature too. 
We have a service with hazelcast reliable topic and we need to consume events through Java/Kotlin/JVM, Python and .NET clients.
For Java, NodeJs, Go and Python reliable topic feature is supported by hazelcast clients.
